service: ttt-mini
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    PROJECTS_TABLE: ${self:service}-projects-${sls:stage}
    INITIATIVES_TABLE: ${self:service}-initiatives-${sls:stage}
    STATUS_LOGS_TABLE: ${self:service}-status-logs-${sls:stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PROJECTS_TABLE}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.INITIATIVES_TABLE}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.STATUS_LOGS_TABLE}

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi:
          method: '*'
          path: '/{proxy+}'
      - httpApi:
          method: 'GET'
          path: '/health'

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    target: node20
    platform: node
    external: []
resources:
  Resources:
    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PROJECTS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: orgId
            AttributeType: S
          - AttributeName: projectId
            AttributeType: S
        KeySchema:
          - AttributeName: orgId
            KeyType: HASH
          - AttributeName: projectId
            KeyType: RANGE

    InitiativesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.INITIATIVES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: orgId
            AttributeType: S
          - AttributeName: initiativeId
            AttributeType: S
        KeySchema:
          - AttributeName: orgId
            KeyType: HASH
          - AttributeName: initiativeId
            KeyType: RANGE

    StatusLogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STATUS_LOGS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: orgId
            AttributeType: S
          - AttributeName: logId
            AttributeType: S
        KeySchema:
          - AttributeName: orgId
            KeyType: HASH
          - AttributeName: logId
            KeyType: RANGE
